### PR TITLE
#158175324 Write blog posts on the health checks site

### PR DESCRIPTION
**Pull request by solnsubuga**
#### What does this PR do?
This PR allows a user to write blog posts on the health checks site.
#### Description of Task to be completed?
- Move pagination buttons on a new line.
#### How should this be manually tested?
- Checkout the branch and start the application `./manage.py runserver`
- Add some blog posts
- Navigate to the blog 
- Buttons should be on a new line.
#### What are the relevant pivotal tracker stories?
[#158175324](https://www.pivotaltracker.com/story/show/158175324)
#### Screenshots (if appropriate)
screen shot 2018-07-16 at 13 14 11

### CODE REVIEW

**Review by john555 — APPROVED** [review]

**Comment by john555** [comment]
- Get rid of "midnight" in the publishing date on `/my-blogs/`.
- On the publishing date's date picker, make it such that it is impossible to select a past date.

**Comment by solnsubuga** [comment]
@john555 Your suggestions have been addressed.

**Comment by john555** [comment]
This is pending.
screen shot 2018-07-16 at 3 17 17 pm

Get rid of the "midnight" text in the publishing date.

**Comment by solnsubuga** [comment]
@john555 I had not seen that. It's also resolved.

**Review by john555 — APPROVED** [review]

**Pull request merged**
