### PR TITLE
#158175313 Nag User for unresolved jobs

### PR DESCRIPTION
**Pull request by wasswa-derick**
#### What does the PR do?
* Issue nags to the user until he resolves the issues

#### Description of Task to be completed?
* When a User's job goes down, the user is sent a notification email informing him of the same. The system keeps nagging the user every so often until they resolve the job that has gone down

#### How should this be manually tested?
* Clone the branch, git clone https://github.com/andela/hc-wits-kla/tree/ft-nag-user-158175313
* In your terminal, cd hc-wits-kla
* In the project directory, activate the environment, source .env
* Install requirements pip install requirements.txt
* Make migrations python manage.py makemigrations
* Run migrations python manage.py migrate
* Serve the application python manage.py runserver
* In the browser, visit, 127.0.0.1:8000/checks/
* In your terminal, open a new tab and listen for alerts by issuing python manage.py sendalerts
* For real email notifications, provide your email configurations in the settings
* In your browser, create a check(s), set Period to 1 minutes and Grace Time to 1 minute, and the nag interval to a few minutes, when the check goes down and a user is notified, if specified nag interval pass without resolving the check, the system nags the user every after specified minutes until they ping the check. Checks that are on nag mode will show a speak icon beside the nag interval time.
* Go to the console and wait for the nags

#### What are the relevant pivotal tracker stories?
- #158175313

#### Screenshots (if appropriate)
Checks on Nag mode

screen shot 2018-07-06 at 10 27 07

screen shot 2018-07-07 at 18 17 26

### CODE REVIEW

**Comment by solnsubuga** [comment]
@wasswa-derick please squash your commits.

**Comment by wasswa-derick** [comment]
@solnsubuga am going to thanks.

**Comment by john555** [comment]
Change "Nag" to "Nag interval" and style it values the same as the value of the grace period to make the value look like something a user would click. (add dotted border on hover)

**Comment by john555** [comment]
The nag interval value does not have a dotted border on hover, as shown below. Please give it a border on hover.
screen shot 2018-07-09 at 4 26 14 pm

**Review by john555 — APPROVED** [review]
LGTM

**Pull request merged**
