### PR TITLE
#158175324 Add writing and sharing of blog posts.

### PR DESCRIPTION
**Pull request by solnsubuga**
#### What does this PR do?
This PR allows allows a user to write blog posts and also visitors to read and comment on published posts.
#### Description of Task to be completed?
This tasks involves creating a basic blog that allows logged in users to create categories, write blog posts and share blog posts.
#### How should this be manually tested?
- Clone the application and install the requirements in requirements.txt `pip install -r requirements.txt`
- Run migrations and then start the application `./manage.py migrate blog` and then `python manage.py runserver`
- You may also need to compress the static files `./manage.py compress`
- Login and navigate to the my posts tab
- Click Add Category button and add a category.
- Click Add post button
- Add posts detail publishing date and time should be today.
- Navigate to the blog tab and view post, click the link to view details and make a comment on it.
#### What are the relevant pivotal tracker stories?
[#158175324](https://www.pivotaltracker.com/story/show/158175324)
#### Screenshots 
screen shot 2018-07-05 at 14 45 13
screen shot 2018-07-05 at 14 45 24
screen shot 2018-07-05 at 15 43 51

screen shot 2018-07-05 at 14 44 38
screen shot 2018-07-05 at 14 44 16

### CODE REVIEW

**Comment by RrNn** [comment]
@solnsubuga this is good work. Perhaps the comment textfield could be made as wide as the post itself, rather than it being half way wide. That would be perfect. So some css is needed there, but again thats awesome so far.

**Comment by solnsubuga** [comment]
@RrNn I had made it take the width of the entire page though it looked ugly to me. Maybe we could centre it.

**Comment by john555** [comment]
Currently,  the blog feature works. However, it is not user-friendly. Here are some things you should do to make it more user-friendly.
- Place 'My Posts' (as a tab) on the Blog page.
- Rename 'My Posts' to 'My blogs'.
- Allow adding categories from the "Blog post" form on the fly, in addition to being able to select existing categories.

**Comment by solnsubuga** [comment]
@john555 I have implemented the changes you suggested.

**Comment by john555** [comment]
- Get rid of "My posts" in the main navigation menu and change the route from `/my-posts/` to `/my-blogs/`. You want to have consistency in the vocabulary.
- Get rid of the "My blogs" link in the main navigation.
- While on the page showing the user's blogs, provide a navigation link back to the main Blog page (at `/blog/`) with all blogs.

**Comment by john555** [comment]
The titles should look the same (same font-size) on the two pages. Here is what they currently look like.
screen shot 2018-07-11 at 2 38 51 pm
screen shot 2018-07-11 at 2 38 41 pm

The markup you used is not Symantic. "My blogs" is the heading and  "All blogs" is a link to another page. It shouldn't be part of the the heading. To a screen reader, or web crawler, the heading would be "My blogs All blogs". 

Rearrange your markup to be like below.
`<h2>Blog</h2> <span> <a class="posts-link" href="/my-blogs/">My blogs</a></span>`

Here is what it currently is.
screen shot 2018-07-11 at 2 38 00 pm

**Pull request closed without merging**
