### PR TITLE
#158175315 Extend the maximum timeout and grace periods

### PR DESCRIPTION
**Pull request by ja-odur**
#### What does this PR do?
* Extends the grace and time-out periods.
#### Description of Task to be completed?
* To extend the maximum time accepted by the `timeout` form to one year.
* Modify UI, so that a user can set these extended periods
#### How should this be manually tested?
* Clone the project from GitHub ```git clone https://github.com/andela/hc-wits-kla.git``` and set it up as indicated in the `README.md` file.
* After cloning, cd into the project directory and run the environment setup in the project README
* Run `python manage.py compress` to recompress the static files.
* Start the project `python manage.py runserver`.
*  Login and add a new check. You should be able to adjust the time-out and grace periods to upto a year as shown in the screenshot below.
#### What are the relevant pivotal tracker stories?
* [#158175315](https://www.pivotaltracker.com/story/show/158175315)
#### Screenshots 

screenshot before the changes
screenshot before

screenshot after the changes
screenshot

### CODE REVIEW

**Comment by solnsubuga** [comment]
For the screenshots, maybe you could add the screenshot before the changes and the one after the changes such that we can quickly glance at the new UI changes.

**Comment by ja-odur** [comment]
@solnsubuga I have added the screenshot before the changes for comparison as you suggested earlier.

**Review by wasswa-derick — COMMENTED** [review]
Seemingly the changes are okay for me.

Have reviewed the changes on the branch and all is well.

**Comment by Yiga-fred** [comment]
The changes look good @ja-odur , good work the screen clearly show what you accomplished

**Review by Yiga-fred — APPROVED** [review]
Good work changes look good

**Review by solnsubuga — APPROVED** [review]
LGTM

**Comment by RrNn** [comment]
@ja-odur this is great work. `time selection` is as smooth as before.

**Review by RrNn — APPROVED** [review]

**Review by john555 — APPROVED** [review]
Good job. Update your PR so that I may merge.

**Pull request merged**
