### PR TITLE
[Feature #158175321] Add Help center with FAQ’s, help videos, live chat

### PR DESCRIPTION
**Pull request by wasswa-derick**
#### What does this PR do?
Adds a help section where a new user can find information Healthchecks i.e. what it does, how it does it, etcetera.

#### Description of Task to be completed?
*  Add a tab that has onboarding content for new users on the dashboard, and a live chat where users can post their questions and a team from healthchecks responds to those questions.
* Add tab onboarding as a drop-down with Faq and tutorials section.
* Add a Live chat section that is collapsible at the bottom right side of the screen.

#### How should this be manually tested?
* Clone the branch, ```git clone https://github.com/andela/hc-wits-kla/tree/ft-onboarding-content-158175321```
* In your terminal, ```cd hc-wits-kla```
* In the project directory, activate the environment, ```source hc-venv/bin/activate```
* Install requirements ```pip install requirements.txt```
* Make migrations ```python manage.py makemigrations```
* Run migrations ```python manage.py migrate```
* Create a superuser by running ``` ./manage.py createsuperuser``` in your terminal
* Serve the application ```python manage.py runserver```
* In the browser, visit, 127.0.0.1:8000/
* Login to Healthchecks and go to your checks page
* Go to 127.0.0.1:8000/admin/ and add FAQS and Tutorials to view them in the tab.
* After adding the FAQS and Tutorials with the superuser privileges, then go the application and click on the onboarding tab. The tutorials link can be youtube's embed links.
* Upload a video on youtube and click share and extra the embedded link from youtube.
* To test the Live chat, let the Live chat widget load and go ahead and send your question or message.
* The Healthchecks admin, then respond to these questions.

#### Any background context you want to provide?
* FAQs and Tutorials can only be added by a superuser
* An available healthchecks agent/administrator will respond to your questions and messages as soon as possible.

#### What are the relevant pivotal tracker stories?
[#158175321](https://www.pivotaltracker.com/story/show/158175321)

#### Screenshots (if appropriate)

FAQS AND TUTORIALS

screen shot 2018-07-13 at 07 47 28

screen shot 2018-07-13 at 08 14 16

screen shot 2018-07-13 at 07 48 07

LIVE CHAT

screen shot 2018-07-13 at 07 47 11

ANSWERING A USER MESSAGE

screen shot 2018-07-16 at 15 22 54

### CODE REVIEW

**Comment by ja-odur** [comment]
@wasswa-derick It's better to make the relevant PT story in the PR, a link for easy follow up.

**Comment by solnsubuga** [comment]
@wasswa-derick I have checked out your work. Though I can't see the information that your screenshots showcase. See attached screenshot here.
screen shot 2018-07-16 at 12 04 33

**Comment by wasswa-derick** [comment]
@solnsubuga 
Follow the instruction in the PR.
Create a superuser, then access Django admin (127.0.0.1:8000/admin/) and add that data from the UI

The FAQs and Tutorials are added by the product admin.

**Comment by john555** [comment]
When adding tutorials, what type of video link is expected? (Add this as a placeholder text in the video link field and add some validation, if possible)
I have tried using a youtube link but it does not work.

**Comment by john555** [comment]
For the live chat, where does the message get sent? Include this in your PR description.

**Review by john555 — APPROVED** [review]

**Pull request merged**
