### PR TITLE
#158175312 Configure and Add Periodic Reports

### PR DESCRIPTION
**Pull request by solnsubuga**
#### What does this PR do?
This PR allows a  user  to configure periodic reports, for example, daily, weekly and monthly and to also view these reports on the dashboard. 

#### Description of Task to be completed?
The task is to add a feature that allows a user to specify when they want to receive reports periodically and also create a view for reports based on the user defined prefences.

#### How should this be manually tested?

- Clone the application and install the requirements in requirements.txt
- Run migrations and then start the application `./manage.py migrate` and then `python manage.py runserver`
- Create account and login
- Navigate to the setting page, subscribe to reports and also set the prefered frequency then save.
- Add a few checks and ping them.
- Go to command line then run   `./manage.py sendreports` Note: Sent email will displayed on cli and number of reports sent
- When logged into application click the reports tab to view a summary of your reports.

#### What are the relevant pivotal tracker stories?
[#158175312](https://www.pivotaltracker.com/story/show/158175312)
#### Screenshots 
Configure periodic report.
screen shot 2018-06-27 at 23 17 41

View report.
screen shot 2018-06-27 at 23 18 02

### CODE REVIEW

**Review by wasswa-derick — COMMENTED** [review]
* Good commit message. 

* Joseph and I have pulled this branch and Realised a small glitch when someone does not check any of the options.

* The first time I ran, it cast the Keyerror and I have tried out with a second user, this time it did not bring the keyerror, rather the default is set to monthly. Could you please investigate it and see if is a concern.

**Review by ja-odur — COMMENTED** [review]
I tried accessing the REPORT link in the nav-bar immediately after setup and it gave me a KeyError exception. Can you set a default period to prevent this exception.

**Comment by solnsubuga** [comment]
@ja-odur have you run the migration? I added the default. I need to catch that error in the view.

**Comment by solnsubuga** [comment]
@ja-odur  I ve updated the instructions to ensure that migrations are run before the starting of the applications. Thank you.

**Review by ja-odur — APPROVED** [review]
works fine. Great work!

**Review by Yiga-fred — APPROVED** [review]
The functionality looks good to me. good work @solnsubuga

**Comment by john555** [comment]
Here are some adjustments you should make reports section in settings.
- Add some spacing between the labels.
- Clicking the label should toggle the radio buttons.

**Comment by solnsubuga** [comment]
@john555  the changes have been worked on.

**Review by john555 — APPROVED** [review]
LGTM

**Comment by RrNn** [comment]
Runs smoothly and as described, but @solnsubuga always remember to specify that we clone the branch in the  **How should this be manually tested?** section of your PR

**Pull request merged**
